import pytest

from src.models import ImplementationPlan, Scenario, TestDesignArtifact, TestDesignOutput
from src.renderer import render_from_plans, render_playwright_skeleton


# --- Helpers ---

def make_artifact(
    scenarios: list[Scenario],
    requirement_title: str = "User Authentication",
) -> TestDesignArtifact:
    return TestDesignArtifact(
        schema_version="1.0",
        source_project="ai-test-design-assistant",
        requirement_title=requirement_title,
        test_design_output=TestDesignOutput(positive_scenarios=scenarios),
    )


def make_scenario(**kwargs) -> Scenario:
    defaults = {
        "id": "TC-POS-001",
        "title": "Login succeeds",
        "expected_result": "User is redirected to dashboard",
    }
    return Scenario(**{**defaults, **kwargs})


# --- File structure ---

def test_output_contains_playwright_import():
    artifact = make_artifact([make_scenario()])
    output = render_playwright_skeleton(artifact)
    assert "import { test, expect } from '@playwright/test';" in output


def test_output_contains_describe_block_named_after_requirement():
    artifact = make_artifact([make_scenario()], requirement_title="User Login")
    output = render_playwright_skeleton(artifact)
    assert "test.describe('User Login'" in output


def test_output_contains_file_header():
    artifact = make_artifact([make_scenario()])
    output = render_playwright_skeleton(artifact)
    assert "Generated by ai-test-implementation-assistant" in output
    assert "This file is a scaffold" in output


def test_output_contains_requirement_title_in_header():
    artifact = make_artifact([make_scenario()], requirement_title="Password Reset")
    output = render_playwright_skeleton(artifact)
    assert "Requirement: Password Reset" in output


def test_output_contains_source_and_schema_version_in_header():
    artifact = make_artifact([make_scenario()])
    output = render_playwright_skeleton(artifact)
    assert "ai-test-design-assistant" in output
    assert "schema_version: 1.0" in output


# --- Scenario rendering ---

def test_scenario_id_appears_in_output():
    artifact = make_artifact([make_scenario(id="TC-POS-042")])
    output = render_playwright_skeleton(artifact)
    assert "TC-POS-042" in output


def test_test_name_is_lowercased_scenario_title():
    artifact = make_artifact([make_scenario(title="Login Succeeds With Valid Credentials")])
    output = render_playwright_skeleton(artifact)
    assert "test('login succeeds with valid credentials'" in output


def test_preconditions_appear_as_comment():
    scenario = make_scenario(preconditions=["User account exists", "User is on login page"])
    artifact = make_artifact([scenario])
    output = render_playwright_skeleton(artifact)
    assert "// Preconditions:" in output
    assert "User account exists" in output
    assert "User is on login page" in output


def test_scenario_without_preconditions_omits_preconditions_line():
    scenario = make_scenario(preconditions=None)
    artifact = make_artifact([scenario])
    output = render_playwright_skeleton(artifact)
    assert "// Preconditions:" not in output


def test_steps_appear_as_numbered_comments():
    scenario = make_scenario(steps=["Navigate to login page", "Enter credentials"])
    artifact = make_artifact([scenario])
    output = render_playwright_skeleton(artifact)
    assert "// Step 1: Navigate to login page" in output
    assert "// Step 2: Enter credentials" in output


def test_scenario_without_steps_renders_todo_placeholder():
    scenario = make_scenario(steps=None)
    artifact = make_artifact([scenario])
    output = render_playwright_skeleton(artifact)
    assert "// TODO: implement test steps" in output


def test_expected_result_appears_as_comment():
    scenario = make_scenario(expected_result="User is redirected to /dashboard")
    artifact = make_artifact([scenario])
    output = render_playwright_skeleton(artifact)
    assert "// Expected: User is redirected to /dashboard" in output


# --- TODO markers ---

def test_todo_markers_present_for_steps():
    scenario = make_scenario(steps=["Click login button"])
    artifact = make_artifact([scenario])
    output = render_playwright_skeleton(artifact)
    assert "// TODO: await page.<action>(...);" in output


def test_todo_markers_present_for_assertion():
    artifact = make_artifact([make_scenario()])
    output = render_playwright_skeleton(artifact)
    assert "// TODO: await expect(page).<matcher>(...);" in output


# --- Multiple scenarios ---

def test_multiple_scenarios_all_rendered():
    scenarios = [
        make_scenario(id="TC-POS-001", title="Login succeeds"),
        make_scenario(id="TC-POS-002", title="Logout succeeds"),
        make_scenario(id="TC-POS-003", title="Session persists after refresh"),
    ]
    artifact = make_artifact(scenarios)
    output = render_playwright_skeleton(artifact)
    assert "TC-POS-001" in output
    assert "TC-POS-002" in output
    assert "TC-POS-003" in output


def test_multiple_scenarios_all_have_test_blocks():
    scenarios = [
        make_scenario(id="TC-POS-001", title="Login succeeds"),
        make_scenario(id="TC-POS-002", title="Logout succeeds"),
    ]
    artifact = make_artifact(scenarios)
    output = render_playwright_skeleton(artifact)
    assert output.count("async ({ page })") == 2


# --- Determinism ---

def test_same_input_produces_same_output():
    artifact = make_artifact([
        make_scenario(
            id="TC-POS-001",
            title="Login succeeds",
            preconditions=["User exists"],
            steps=["Navigate", "Submit"],
            expected_result="Redirected",
        )
    ])
    first = render_playwright_skeleton(artifact)
    second = render_playwright_skeleton(artifact)
    assert first == second


# =============================================================================
# Phase 2: render_from_plans
# =============================================================================

def make_plan(**kwargs) -> ImplementationPlan:
    defaults = {
        "scenario_id": "TC-POS-001",
        "test_name": "should successfully log in with valid credentials",
        "arrange": ["A registered user account exists"],
        "act": ["Navigate to login page", "Enter credentials", "Click submit"],
        "assert_steps": ["The user is redirected to the dashboard"],
        "notes": None,
    }
    return ImplementationPlan(**{**defaults, **kwargs})


# --- File structure (shared with Phase 1) ---

def test_plans_output_contains_playwright_import():
    output = render_from_plans(make_artifact([make_scenario()]), [make_plan()])
    assert "import { test, expect } from '@playwright/test';" in output


def test_plans_output_contains_describe_block():
    output = render_from_plans(
        make_artifact([make_scenario()], requirement_title="User Login"),
        [make_plan()],
    )
    assert "test.describe('User Login'" in output


def test_plans_output_contains_file_header():
    output = render_from_plans(make_artifact([make_scenario()]), [make_plan()])
    assert "Generated by ai-test-implementation-assistant" in output
    assert "This file is a scaffold" in output


# --- Plan-based test block rendering ---

def test_plan_scenario_id_appears_in_output():
    output = render_from_plans(
        make_artifact([make_scenario(id="TC-POS-007")]),
        [make_plan(scenario_id="TC-POS-007")],
    )
    assert "TC-POS-007" in output


def test_plan_test_name_used_verbatim():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(test_name="should log in successfully")],
    )
    assert "test('should log in successfully'" in output


def test_plan_test_name_is_not_lowercased_title():
    # Phase 2 uses the AI-provided test_name directly, not a derived lowercase title
    output = render_from_plans(
        make_artifact([make_scenario(title="Login Succeeds")]),
        [make_plan(test_name="should successfully log in")],
    )
    assert "test('should successfully log in'" in output
    assert "test('login succeeds'" not in output


# --- AAA section headers ---

def test_arrange_section_header_present():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(arrange=["Navigate to login page"])],
    )
    assert "// Arrange" in output


def test_act_section_header_present():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(act=["Click submit"])],
    )
    assert "// Act" in output


def test_assert_section_header_present():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(assert_steps=["User is on dashboard"])],
    )
    assert "// Assert" in output


def test_arrange_section_omitted_when_empty():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(arrange=[])],
    )
    assert "// Arrange" not in output


# --- Step content ---

def test_arrange_steps_appear_in_output():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(arrange=["A user account exists", "User is on login page"])],
    )
    assert "A user account exists" in output
    assert "User is on login page" in output


def test_act_steps_appear_in_output():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(act=["Enter email address", "Enter password"])],
    )
    assert "Enter email address" in output
    assert "Enter password" in output


def test_assert_steps_appear_in_output():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(assert_steps=["User is redirected to /dashboard", "Username is displayed"])],
    )
    assert "User is redirected to /dashboard" in output
    assert "Username is displayed" in output


# --- TODO markers ---

def test_action_todo_markers_present_in_act_section():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(act=["Click submit"])],
    )
    assert "// TODO: await page.<action>(...);" in output


def test_matcher_todo_markers_present_in_assert_section():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(assert_steps=["User is on dashboard"])],
    )
    assert "// TODO: await expect(page).<matcher>(...);" in output


# --- Notes ---

def test_notes_appear_when_present():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(notes="Clarify whether redirect is client-side or server-side")],
    )
    assert "// [NOTE]" in output
    assert "Clarify whether redirect is client-side or server-side" in output


def test_notes_absent_when_none():
    output = render_from_plans(
        make_artifact([make_scenario()]),
        [make_plan(notes=None)],
    )
    assert "// [NOTE]" not in output


# --- Multiple plans ---

def test_multiple_plans_all_rendered():
    plans = [
        make_plan(scenario_id="TC-POS-001", test_name="should log in"),
        make_plan(scenario_id="TC-POS-002", test_name="should log out"),
    ]
    artifact = make_artifact([
        make_scenario(id="TC-POS-001"),
        make_scenario(id="TC-POS-002"),
    ])
    output = render_from_plans(artifact, plans)
    assert "TC-POS-001" in output
    assert "TC-POS-002" in output
    assert output.count("async ({ page })") == 2


# --- Determinism ---

def test_render_from_plans_is_deterministic():
    artifact = make_artifact([make_scenario()])
    plans = [make_plan(
        arrange=["Setup user"],
        act=["Navigate", "Click"],
        assert_steps=["Check URL"],
        notes="Some note",
    )]
    assert render_from_plans(artifact, plans) == render_from_plans(artifact, plans)
