from src.models import ImplementationPlan, Scenario, TestDesignArtifact

_PLAYWRIGHT_IMPORT = "import { test, expect } from '@playwright/test';"
_TOOL_NAME = "ai-test-implementation-assistant"


def _normalize_test_name(title: str) -> str:
    """Derive a test name from a scenario title deterministically.

    Lowercases and strips the title. Single quotes are escaped to prevent
    breaking the generated TypeScript string literal.
    """
    return title.lower().strip().replace("'", "\\'")


def _render_scenario(scenario: Scenario, indent: str = "  ") -> str:
    inner = indent + "  "
    lines: list[str] = []

    # Scenario metadata header
    lines.append(f"{indent}// {scenario.id} | {scenario.title}")

    if scenario.preconditions:
        preconditions_str = " | ".join(scenario.preconditions)
        lines.append(f"{indent}// Preconditions: {preconditions_str}")

    test_name = _normalize_test_name(scenario.title)
    lines.append(f"{indent}test('{test_name}', async ({{ page }}) => {{")

    # Steps as numbered TODO comments
    if scenario.steps:
        for i, step in enumerate(scenario.steps, start=1):
            lines.append(f"{inner}// Step {i}: {step}")
            lines.append(f"{inner}// TODO: await page.<action>(...);")
            lines.append("")
    else:
        lines.append(f"{inner}// TODO: implement test steps")
        lines.append("")

    # Expected result as assertion placeholder
    lines.append(f"{inner}// Expected: {scenario.expected_result}")
    lines.append(f"{inner}// TODO: await expect(page).<matcher>(...);")

    lines.append(f"{indent}}});")

    return "\n".join(lines)


def _render_plan(plan: ImplementationPlan, indent: str = "  ") -> str:
    inner = indent + "  "
    test_name = plan.test_name.replace("'", "\\'")

    body_sections: list[list[str]] = []

    if plan.notes:
        body_sections.append([f"{inner}// [NOTE] {plan.notes}"])

    if plan.arrange:
        section = [f"{inner}// Arrange"]
        for step in plan.arrange:
            section.append(f"{inner}// {step}")
            section.append(f"{inner}// TODO: await page.<action>(...);")
        body_sections.append(section)

    if plan.act:
        section = [f"{inner}// Act"]
        for step in plan.act:
            section.append(f"{inner}// {step}")
            section.append(f"{inner}// TODO: await page.<action>(...);")
        body_sections.append(section)

    if plan.assert_steps:
        section = [f"{inner}// Assert"]
        for step in plan.assert_steps:
            section.append(f"{inner}// {step}")
            section.append(f"{inner}// TODO: await expect(page).<matcher>(...);")
        body_sections.append(section)

    lines: list[str] = [
        f"{indent}// {plan.scenario_id}",
        f"{indent}test('{test_name}', async ({{ page }}) => {{",
    ]

    for i, section in enumerate(body_sections):
        lines.extend(section)
        if i < len(body_sections) - 1:
            lines.append("")

    lines.append(f"{indent}}});")
    return "\n".join(lines)


def render_from_plans(
    artifact: TestDesignArtifact,
    plans: list[ImplementationPlan],
) -> str:
    """Render a Playwright .spec.ts skeleton from AI-generated implementation plans.

    Uses the AAA (Arrange / Act / Assert) structure derived from the plans.
    The artifact is used for the file header only; test block content comes
    entirely from the plans.

    This function is deterministic: the same input always produces the same output.
    """
    lines: list[str] = []

    lines.append(f"// Generated by {_TOOL_NAME}")
    lines.append(f"// Requirement: {artifact.requirement_title}")
    lines.append(
        f"// Source: {artifact.source_project} | schema_version: {artifact.schema_version}"
    )
    lines.append("// This file is a scaffold. All TODO markers require implementation.")
    lines.append("")

    lines.append(_PLAYWRIGHT_IMPORT)
    lines.append("")

    lines.append(f"test.describe('{artifact.requirement_title}', () => {{")
    lines.append("")

    for i, plan in enumerate(plans):
        lines.append(_render_plan(plan))
        if i < len(plans) - 1:
            lines.append("")

    lines.append("")
    lines.append("});")
    lines.append("")

    return "\n".join(lines)


def render_playwright_skeleton(artifact: TestDesignArtifact) -> str:
    """Render a Playwright .spec.ts skeleton from a validated test design artifact.

    This function is deterministic: the same input always produces the same output.
    No AI involvement. Suitable for unit testing without mocking.
    """
    lines: list[str] = []

    # File header
    lines.append(f"// Generated by {_TOOL_NAME}")
    lines.append(f"// Requirement: {artifact.requirement_title}")
    lines.append(
        f"// Source: {artifact.source_project} | schema_version: {artifact.schema_version}"
    )
    lines.append("// This file is a scaffold. All TODO markers require implementation.")
    lines.append("")

    lines.append(_PLAYWRIGHT_IMPORT)
    lines.append("")

    lines.append(f"test.describe('{artifact.requirement_title}', () => {{")
    lines.append("")

    scenarios = artifact.test_design_output.positive_scenarios
    for i, scenario in enumerate(scenarios):
        lines.append(_render_scenario(scenario))
        if i < len(scenarios) - 1:
            lines.append("")

    lines.append("")
    lines.append("});")
    lines.append("")

    return "\n".join(lines)
